name: CI

on: 
  push:
jobs:
  job1:
    runs-on: ubuntu-18.04
    steps:
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Echo
      uses: docker://ubuntu:19.04
      with:
        entrypoint: /bin/bash
        args: -c "
              echo Hello World
              && export DEBIAN_FRONTEND=noninteractive
              && mkdir -p $HOME
              && cd $HOME
              && apt-get update
              && apt-get -qq -y install git make
              && git clone https://github.com/steve-cs/gnat-builder.git
              && cd gnat-builder
              && make prefix=/usr/local release-install
              && which gcc
              && gcc -v
              "
