name: CI
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 12 * * *'
jobs:
  bootstrap:
    runs-on: ubuntu-20.04
    steps:
    - name: Makefile
      run: |
        apt-get update
        DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
        apt-get -qq -y install git make
        git clone https://github.com/steve-cs/gnat-builder.git
        cp -r gnat-builder/* .

    - name: Depends
      run: make depends

    - name: GCC
      run: make gcc gcc-install gcc-build-clean

    - name: GPRbuild bootstrap
      run: make gprbuild-bootstrap gprbuild-bootstrap-install gprbuild-bootstrap-clean 

    - name: XML/Ada
      run: make xmlada xmlada-install xmlada-clean

    - name: GPRBUILD
      run: make gprbuild gprbuild-install gprbuild-clean

    - name: GNATColl
      run: |
        make gnatcoll-core gnatcoll-core-install gnatcoll-core-clean
        make gnatcoll-bindings gnatcoll-bindings-install gnatcoll-bindings-clean
        make gnatcoll-sql gnatcoll-sql-install
        make gnatcoll-db-build
        make gnatcoll-gnatcoll_db2ada gnatcoll-gnatcoll_db2ada-install
        make gnatcoll-sqlite gnatcoll-sqlite-install
        make gnatcoll-xref gnatcoll-xref-install
        make gnatcoll-gnatinspect gnatcoll-gnatinspect-install
        make gnatcoll-db-clean
        
    - name: LibAdaLang
      run: |
        make langkit langkit-install
        make libadalang libadalang-install
        make libadalang-clean langkit-clean

    - name: GTKAda
      run: make gtkada gtkada-install gtkada-clean

    - name: GPS
      run: |
        make gps gps-install
        make gps-clean libadalang-tools-clean ada_language_server-clean vss-clean spawn-clean

    - name: SPARK 2014
      run: make spark2014 spark2014-install spark2014-clean

  gnat-builder:
    runs-on: ubuntu-18.04
    container: 
      image: docker://ubuntu:20.04
    steps:
    - name: Makefile
      run: |
        apt-get update
        DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
        apt-get -qq -y install git make
        git clone https://github.com/steve-cs/gnat-builder.git
        cp -r gnat-builder/* .

    - name: Release
      run: make release-install

  xmlada:
    runs-on: ubuntu-18.04
    container: 
      image: docker://ubuntu:20.04
    steps:
    - name: Makefile
      run: |
        apt-get update
        DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
        apt-get -qq -y install git make
        git clone https://github.com/steve-cs/gnat-builder.git
        cp -r gnat-builder/* .

    - name: Release
      run: make release-install

    - name: Build
      run: make xmlada

  gprbuild:
    runs-on: ubuntu-18.04
    container: 
      image: docker://ubuntu:20.04
    steps:
    - name: Makefile
      run: |
        apt-get update
        DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
        apt-get -qq -y install git make
        git clone https://github.com/steve-cs/gnat-builder.git
        cp -r gnat-builder/* .

    - name: Release
      run: make release-install

    - name: Build
      run: make gprbuild
      
  gnatcoll-core:
    runs-on: ubuntu-18.04
    container: 
      image: docker://ubuntu:20.04
    steps:
    - name: Makefile
      run: |
        apt-get update
        DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
        apt-get -qq -y install git make
        git clone https://github.com/steve-cs/gnat-builder.git
        cp -r gnat-builder/* .

    - name: Release
      run: make release-install

    - name: Build
      run: make gnatcoll-core

  gnatcoll-bindings:
    runs-on: ubuntu-18.04
    container: 
      image: docker://ubuntu:20.04
    steps:
    - name: Makefile
      run: |
        apt-get update
        DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
        apt-get -qq -y install git make
        git clone https://github.com/steve-cs/gnat-builder.git
        cp -r gnat-builder/* .

    - name: Release
      run: make release-install

    - name: Build
      run: make gnatcoll-bindings

  gnatcoll-db:
    runs-on: ubuntu-18.04
    container: 
      image: docker://ubuntu:20.04
    steps:
    - name: Makefile
      run: |
        apt-get update
        DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
        apt-get -qq -y install git make
        git clone https://github.com/steve-cs/gnat-builder.git
        cp -r gnat-builder/* .

    - name: Release
      run: make release-install

    - name: Build
      run: make gnatcoll-db

  langkit:
    runs-on: ubuntu-18.04
    container: 
      image: docker://ubuntu:20.04
    steps:
    - name: Makefile
      run: |
        apt-get update
        DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
        apt-get -qq -y install git make
        git clone https://github.com/steve-cs/gnat-builder.git
        cp -r gnat-builder/* .

    - name: Release
      run: make release-install

    - name: Build
      run: make langkit

  libadalang:
    runs-on: ubuntu-18.04
    container: 
      image: docker://ubuntu:20.04
    steps:
    - name: Makefile
      run: |
        apt-get update
        DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
        apt-get -qq -y install git make
        git clone https://github.com/steve-cs/gnat-builder.git
        cp -r gnat-builder/* .

    - name: Release
      run: make release-install

    - name: Build
      run: make libadalang

  gtkada:
    runs-on: ubuntu-18.04
    container: 
      image: docker://ubuntu:20.04
    steps:
    - name: Makefile
      run: |
        apt-get update
        DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
        apt-get -qq -y install git make
        git clone https://github.com/steve-cs/gnat-builder.git
        cp -r gnat-builder/* .

    - name: Release
      run: make release-install

    - name: Build
      run: make gtkada

  gps:
    runs-on: ubuntu-18.04
    container: 
      image: docker://ubuntu:20.04
    steps:
    - name: Makefile
      run: |
        apt-get update
        DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
        apt-get -qq -y install git make
        git clone https://github.com/steve-cs/gnat-builder.git
        cp -r gnat-builder/* .

    - name: Release
      run: make release-install

    - name: Build
      run: make gps

  spark2014:
    runs-on: ubuntu-18.04
    container: 
      image: docker://ubuntu:20.04
    steps:
    - name: Makefile
      run: |
        apt-get update
        DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata
        apt-get -qq -y install git make
        git clone https://github.com/steve-cs/gnat-builder.git
        cp -r gnat-builder/* .

    - name: Release
      run: make release-install

    - name: Build
      run: make spark2014
