name: CI

on:
  push:
  schedule:
    - cron:  '50 4 * * *'
jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    - master
    - release/*
or only run on pull_request events that target the master branch:

on:
