name: CI
on:
  push:
  schedule:
    - cron:  '0 12 * * *'
jobs:
  job1:
    runs-on: ubuntu-18.04
    container: 
      image: docker://ubuntu:18.04
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
    - name: Makefile
      run: |
        apt-get update
        apt-get -qq -y install git make
        git clone https://github.com/steve-cs/gnat-builder.git
        cp gnat-builder/Makefile .

    - name: Depends
      run: make depends

    - name: GCC
      run: make gcc gcc-install

    - name: GPRbuild bootstrap
      run: make gprbuild-bootstrap-install 

    - name: XML/Ada
      run: make xmlada xmlada-install

    - name: GPRBUILD
      run: make gprbuild gprbuild-install

    - name: GNATColl
      run: |
        make gnatcoll-core gnatcoll-core-install
        make gnatcoll-bindings gnatcoll-bindings-install
        make gnatcoll-sql gnatcoll-sql-install
        make gnatcoll-db-build
        make gnatcoll-gnatcoll_db2ada gnatcoll-gnatcoll_db2ada-install
        make gnatcoll-sqlite gnatcoll-sqlite-install
        make gnatcoll-xref gnatcoll-xref-install
        make gnatcoll-gnatinspect gnatcoll-gnatinspect-install
    - name: LibAdaLang
      run: make libadalang libadalang-install

    - name: GTKAda
      run: make gtkada gtkada-install

    - name: GPS
      run: make gps gps-install

    - name: SPARK 2014
      run: make spark2014 spark2014-install
