name: CI
on: 
  push:
jobs:
  job1:
    container: docker://ubuntu:18.04
    steps:
    - run: echo Hello World
    - run: touch bozo
    - run: ls -l .
    - run: touch /usr/local/bozo
    - run: ls -l /usr/local/bozo
