name: CI

on: 
  push:
jobs:
  job1:
    runs-on: ubuntu-18.04
    steps:
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Environment
      uses: docker://ubuntu:19.04
      run: |
        uname -a
        echo $PWD
        ls -lR
        ls -l /
        ls -lR /github
    - name: Inside a docker container
      uses: docker://ubuntu:19.04
      run: |
        uname -a
        echo $PWD
        ls -lR
        ls -l /
        ls -lR /github
      
    
