name: CI
on: 
  push:
jobs:
  job1:
    runs-on: ubuntu-18.04
    container: 
      image: docker://ubuntu:18.04
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
    - run: echo Hello World
    - run: echo $DEBIAN_FRONTEND
    - run: touch bozo
    - run: ls -l .
    - run: touch /usr/local/bozo
    - run: ls -l /usr/local/bozo
