name: CI
on: 
  push:
jobs:
  job1:
    runs-on: ubuntu-18.04
    container: 
      image: docker://ubuntu:18.04
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
    - name: First Step
      run: apt-get update
      run: apt-get -qq -y install git make
      run: git clone https://github.com/steve-cs/gnat-builder.git
      run: cd gnat-builder
      run: make depends
      
